{
 "title": "Elasticsearch Exporter: /_cat/fielddata",
 "description": "Most fields are indexed by default, which makes them searchable. Sorting, aggregations, and accessing field values in scripts, however, requires a different access pattern from search.",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(elasticsearch_cat_indices_docs_count{cluster=~\"$cluster\"}, index)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(elasticsearch_cat_nodes_cpu, node_role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health: /_cluster/health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Elasticsearch nodes count" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})",
     "legendFormat": "total nodes"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})",
     "legendFormat": "data nodes"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Elasticsearch shards count" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Active shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Primary shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards_percent_as_number{cluster=~\"$cluster\"})",
     "legendFormat": "% Active shards"
    }
   ]
  },
  { "title": "Fielddata: /_cat/fielddata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fielddata size",
   "type": "graph",
   "description": "Field data usage\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-fielddata.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_fielddata_size{cluster=~\"$cluster\"}) by (field)",
     "legendFormat": "{{field}}"
    }
   ]
  }
 ]
}