{
 "title": "Elasticsearch Exporter: /_cat/recovery",
 "description": "Returns information about ongoing and completed shard recoveries, similar to the index recovery API.",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "query_result(increase(elasticsearch_cat_recovery_files_total{cluster=~\"$cluster\"}[${__range_s}s]) > 0)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(elasticsearch_cat_nodes_cpu, node_role)"
    }
   },
   {
    "name": "shard",
    "query": "label_values(elasticsearch_cat_segments_docs_count{cluster=~\"$cluster\"}, shard)"
   },
   {
    "name": "stage",
    "query": {
     "query": "label_values(elasticsearch_cat_recovery_bytes_bytes{cluster=~\"$cluster\"}, stage)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health: /_cluster/health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch nodes count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})",
       "legendFormat": "total nodes"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})",
       "legendFormat": "data nodes"
      }
     ]
    },
    {
     "title": "Shards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch shards count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})",
       "legendFormat": "Active shards"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})",
       "legendFormat": "Primary shards"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_active_shards_percent_as_number{cluster=~\"$cluster\"})",
       "legendFormat": "% Active shards"
      }
     ]
    }
   ]
  },
  { "title": "Recovery main: /_cat/recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Percent of bytes recovered",
   "type": "graph",
   "description": "Percent of bytes recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "Recovered percent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_bytes_percent{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total number of files",
   "type": "graph",
   "description": "Total number of files\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_files_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (shard, index, stage, type)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Percent of files recovered",
   "type": "graph",
   "description": "Percent of files recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "Recovered percent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_files_percent{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Bytes to recover",
   "type": "graph",
   "description": "Number of bytes to recover\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_recovery_bytes_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}[$time])) by (shard, index, stage, type)",
     "legendFormat": "shard: {{shard}} stage: {{stage}} type: {{type}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Bytes total",
   "type": "graph",
   "description": "Total number of bytes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_recovery_bytes_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}[$time])) by (shard, index, stage, type)",
     "legendFormat": "shard: {{shard}} stage: {{stage}} type: {{type}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Recovery time",
   "type": "graph",
   "description": "Recovery time\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_recovery_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}[$time]) / increase(elasticsearch_cat_recovery_files_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}[$time])) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Files to recover",
   "type": "graph",
   "description": "Number of files to recover\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_files{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (shard, index, stage, type)",
     "legendFormat": "shard: {{shard}} stage: {{stage}} type: {{type}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Bytes to recovered",
   "type": "graph",
   "description": "Bytes recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_recovery_bytes_recovered{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}[$time])) by (shard, index, stage, type)",
     "legendFormat": "shard: {{shard}} stage: {{stage}} type: {{type}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Recovered files",
   "type": "graph",
   "description": "Number of files to recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_files_recovered{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (shard, index, stage, type)",
     "legendFormat": "shard: {{shard}} stage: {{stage}} type: {{type}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Recovery translog: /_cat/recovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Translog opts to recover",
   "type": "graph",
   "description": "Number of translog ops to recover\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_translog_ops{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Translog opts to recovered",
   "type": "graph",
   "description": "Number of translog ops to recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_translog_ops_recovered{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Percent of translog ops recovered",
   "type": "graph",
   "description": "Percent of translog ops recovered\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html#cat-recovery-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent", "label": "Operations percent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_recovery_translog_ops_percent{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\", stage=~\"$stage\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}