{
 "title": "Elasticsearch Exporter: /_cat/shards",
 "description": "The shards command is the detailed view of what nodes contain which shards. It will tell you if it’s a primary or replica, the number of docs, the bytes it takes on disk, and the node where it’s located.",
 "tags": [
  "elasticsearch",
  "documents",
  "shards",
  "segments"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "query_result(increase(elasticsearch_cat_shards_docs{cluster=~\"$cluster\"}[${__range_s}s]) > 0)\n\n"
    }
   },
   {
    "name": "shard",
    "query": "query_result(increase(elasticsearch_cat_shards_docs{cluster=~\"$cluster\", index=~\"$index\"}[${__range_s}s]) > 0)\n\n"
   }
  ]
 },
 "panels": [
  { "title": "Shards main: /_cat/shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shards documents",
   "type": "graph",
   "description": "Number of docs in shard\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_docs{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard indexing: current",
   "type": "graph",
   "description": "Number of current indexing ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_indexing_index_current{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard flush total",
   "type": "graph",
   "description": "Number of flushes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_flush_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard indexing delete total",
   "type": "graph",
   "description": "Number of delete ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_indexing_delete_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard fielddata cache",
   "type": "graph",
   "description": "Used fielddata cache\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_fielddata_memory_size{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard indexing time",
   "type": "graph",
   "description": "Time spent in indexing\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_indexing_index_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_indexing_index_current{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard flush time",
   "type": "graph",
   "description": "Time spent in flush\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_flush_total_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_flush_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard indexing delete time",
   "type": "graph",
   "description": "Time spent in deletions\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_indexing_delete_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])  / increase(elasticsearch_cat_shards_indexing_delete_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Shard query cache memory",
   "type": "graph",
   "description": "Used query cache\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_query_cache_memory_size{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard indexing failed",
   "type": "graph",
   "description": "Number of failed indexing ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_indexing_index_failed{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards query cache evictions",
   "type": "graph",
   "description": "Query cache evictions\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_query_cache_evictions{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  { "title": "Shards merges: /_cat/shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Shard merges: current",
   "type": "graph",
   "description": "Number of current merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_merges_current{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard document merges: current",
   "type": "graph",
   "description": "Number of current merging docs\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_shards_merges_current_docs{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard merge size",
   "type": "graph",
   "description": "Size of current merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_shards_merges_current_size{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards total merges",
   "type": "graph",
   "description": "Number of docs in shard\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_merges_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shards total documents merges",
   "type": "graph",
   "description": "Docs merged\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_shards_merges_total_docs{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard merge total size",
   "type": "graph",
   "description": "Size of merged\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_cat_shards_merges_total_size{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards merge time",
   "type": "graph",
   "description": "Time spent in merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_merges_total_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / max(increase(elasticsearch_cat_shards_merges_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shards: /_cat/shards store & misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Shard store size",
   "type": "graph",
   "description": "Store size of shard (how much disk it uses)\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_store_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards warmer total",
   "type": "graph",
   "description": "Total warmer ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_warmer_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shards open search contexts",
   "type": "graph",
   "description": "Open search contexts\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_search_open_contexts{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard warmer time",
   "type": "graph",
   "description": "Time spent in warmers\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_warmer_total_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_warmer_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards: /_cat/shards query, fetch & refresh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "Shard fetch phase: current",
   "type": "graph",
   "description": "Current fetch phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_search_fetch_current{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard query phase: current",
   "type": "graph",
   "description": "Current query phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_search_query_current{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shards refresh total",
   "type": "graph",
   "description": "Total refreshes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_refresh_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard external refresh time",
   "type": "graph",
   "description": "Time spent in external refreshes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_refresh_external_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_refresh_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shards query total",
   "type": "graph",
   "description": "Total query phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_search_query_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shards fetch total",
   "type": "graph",
   "description": "Total fetch phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_search_fetch_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard refresh time",
   "type": "graph",
   "description": "Time spent in refreshes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_refresh_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_refresh_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard query phase time",
   "type": "graph",
   "description": "Time spent in query phase\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_search_query_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_search_query_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard fetch phase time",
   "type": "graph",
   "description": "Time spent in fetch phase\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_search_fetch_time_seconds{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time]) / increase(elasticsearch_cat_shards_search_fetch_total{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  { "title": "Shards: /_cat/shards segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Shards segments count",
   "type": "graph",
   "description": "Number of segments\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_segments_count{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard segments index writer memory",
   "type": "graph",
   "description": "Memory used by index writer\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 101 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_segments_index_writer_memory_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard segments fixed bitset memory",
   "type": "graph",
   "description": "Memory used by fixed bit sets for nested object field types and type filters for types referred in _parent fields\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_segments_fixed_bitset_memory_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard segments version map memory",
   "type": "graph",
   "description": "Memory used by version map\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 101 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_segments_version_map_memory_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  {
   "title": "Shard segments used memory",
   "type": "graph",
   "description": "Memory used by segments\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_shards_segments_memory_bytes{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}) by (shard, index)",
     "legendFormat": "shard: {{shard}} index: {{index}}"
    }
   ]
  },
  { "title": "Shards: /_cat/shards sequence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Shard sequence global checkpoint",
   "type": "graph",
   "description": "Global checkpoint\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Sequence" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_seq_no_global_checkpoint{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard sequence local checkpoint",
   "type": "graph",
   "description": "Local checkpoint\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Sequence" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_seq_no_local_checkpoint{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  },
  {
   "title": "Shard sequence max",
   "type": "graph",
   "description": "Max sequence number\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Sequence" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_shards_seq_no_max{cluster=~\"$cluster\", index=~\"$index\", shard=~\"$shard\"}[$time])) by (shard, index)",
     "legendFormat": "shard {{shard}} index {{index}}"
    }
   ]
  }
 ]
}