{
 "title": "Elasticsearch Exporter: /_cat/segments",
 "description": "Returns low-level information about the Lucene segments in index shards, similar to the indices segments API.",
 "tags": [
  "elasticsearch",
  "system"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "query_result(increase(elasticsearch_cat_segments_docs_count{cluster=~\"$cluster\"}[${__range_s}s]) > 0)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(elasticsearch_cat_nodes_cpu, node_role)"
    }
   },
   {
    "name": "shard",
    "query": "query_result(increase(elasticsearch_cat_segments_docs_count{cluster=~\"$cluster\", index=~\"$index\"}[${__range_s}s]) > 0)"
   }
  ]
 },
 "panels": [
  { "title": "Segments: /_cat/segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segments documents count",
   "type": "graph",
   "description": "Number of docs in segment\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-segments.html#cat-segments-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_segments_docs_count{cluster=~\"$cluster\", shard=~\"$shard\"}[$time])) by (index, shard)",
     "legendFormat": "Shard {{shard}}: {{index}}"
    }
   ]
  },
  {
   "title": "Segments documents deleted count",
   "type": "graph",
   "description": "Number of deleted docs in segment\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-segments.html#cat-segments-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_segments_docs_deleted{cluster=~\"$cluster\", shard=~\"$shard\"}[$time])) by (index, shard)",
     "legendFormat": "Shard {{shard}}: {{index}}"
    }
   ]
  },
  {
   "title": "Segment generation",
   "type": "graph",
   "description": "Segment generation\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-segments.html#cat-segments-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_segments_generation{cluster=~\"$cluster\", shard=~\"$shard\"}) by (index, shard)",
     "legendFormat": "Shard {{shard}}: {{index}}"
    }
   ]
  },
  {
   "title": "Sements size",
   "type": "graph",
   "description": "Segment size in bytes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-segments.html#cat-segments-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_segments_size{cluster=~\"$cluster\", shard=~\"$shard\"}) by (index, name)",
     "legendFormat": "Shard {{shard}}: {{index}}"
    }
   ]
  },
  {
   "title": "Sements memory size",
   "type": "graph",
   "description": "Segment memory in bytes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-segments.html#cat-segments-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_segments_size_memory_bytes{cluster=~\"$cluster\", shard=~\"$shard\"}) by (index, name)",
     "legendFormat": "Shard {{shard}}: {{index}}"
    }
   ]
  }
 ]
}