{
 "title": "Elasticsearch Exporter: /_cat/nodes",
 "description": "Returns information about a cluster’s nodes.",
 "tags": [
  "elasticsearch",
  "query",
  "nodes",
  "cpu",
  "system",
  "fetch",
  "segments"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(elasticsearch_cat_indices_docs_count{cluster=~\"$cluster\"}, index)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(elasticsearch_cat_nodes_cpu, node_role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health: /_cluster/health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch nodes count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})",
       "legendFormat": "total nodes"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})",
       "legendFormat": "data nodes"
      }
     ]
    },
    {
     "title": "Shards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch shards count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})",
       "legendFormat": "Active shards"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})",
       "legendFormat": "Primary shards"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_active_shards_percent_as_number{cluster=~\"$cluster\"})",
       "legendFormat": "% Active shards"
      }
     ]
    }
   ]
  },
  { "title": "Nodes main: /_cat/nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Recent CPU usage\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage in percent" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_cpu{cluster=~\"$cluster\", node_role=~\"$role\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "heatmap",
   "description": "Recent CPU usage\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_disk_used_percent{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)"
    }
   ]
  },
  {
   "title": "Disk total/used",
   "type": "graph",
   "description": "Total disk space / used disk space\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max(elasticsearch_cat_nodes_disk_total{cluster=~\"$cluster\", node_role=~\"$role\"}) by (ip))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(max(elasticsearch_cat_nodes_disk_used_bytes{cluster=~\"$cluster\", node_role=~\"$role\"}) by (ip))",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Nodes: /_cat/nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Used HEAP percent",
   "type": "heatmap",
   "description": "Used heap ratio\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_heap_percent{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "description": "Used machine memory ratio\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "RAM usage in percent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_ram_percent{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used file descriptors (fd)",
   "type": "heatmap",
   "description": "Used file descriptors\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_file_desc_percent{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)"
    }
   ]
  },
  {
   "title": "Nodes: /_cat/nodes query & fetch, refresh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Query phase: current",
   "type": "graph",
   "description": "Current query phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_search_query_current{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch phase: current",
   "type": "graph",
   "description": "Current fetch phase ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_search_fetch_current{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Refresh total",
   "type": "graph",
   "description": "Total refreshes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_refresh_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query index total",
   "type": "graph",
   "description": "Total query ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_search_query_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch index total",
   "type": "graph",
   "description": "Total fetch ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_search_fetch_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "External refresh total",
   "type": "graph",
   "description": "Total external refreshes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_refresh_external_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes: /_cat/nodes indexing & merges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing: current",
     "type": "graph",
     "description": "Number of current indexing ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_nodes_indexing_index_current{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges: current",
     "type": "graph",
     "description": "Number of current merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "ops", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_nodes_merges_current{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges current size",
     "type": "graph",
     "description": "Size of current merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_merges_current_size{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fielddata memory",
     "type": "graph",
     "description": "Used fielddata cache\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_fielddata_memory_size{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing index total",
     "type": "graph",
     "description": "Number of indexing ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_indexing_index_total{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges index total",
     "type": "graph",
     "description": "Number of completed merge ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_merges_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges total size",
     "type": "graph",
     "description": "Size merged\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_merges_total_size{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Script compilations",
     "type": "graph",
     "description": "Script compilations\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "ops", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_nodes_script_compilations{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing delete total",
     "type": "graph",
     "description": "Number of delete ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_indexing_delete_total{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges: current merging documents",
     "type": "graph",
     "description": "Number of current merging docs\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_merges_current_docs{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Open contexts",
     "type": "graph",
     "description": "Open search contexts\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "ops", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_nodes_search_open_contexts{cluster=~\"$cluster\", node_role=~\"$role\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing failed",
     "type": "graph",
     "description": "Number of failed indexing ops\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_indexing_index_failed{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges total documents",
     "type": "graph",
     "description": "Docs merged\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes-api-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_nodes_merges_total_docs{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes: /_cat/nodes fetch & query, cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request cache hit ratio",
     "type": "graph",
     "description": "Request cache hit counts / Request cache miss counts\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit", "label": "Hit ratio" }
     ],
     "targets": [
      {
       "expr": "min(increase(elasticsearch_cat_nodes_request_cache_hit_count{cluster=~\"$cluster\"}[$__interval]) / (increase(elasticsearch_cat_nodes_request_cache_hit_count{cluster=~\"$cluster\"}[$__interval]) + increase(elasticsearch_cat_nodes_request_cache_miss_count{cluster=~\"$cluster\"}[$__interval]))) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request cache size",
     "type": "graph",
     "description": "Used request cache\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_request_cache_memory_size{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "description": "Query request cache\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_query_cache_memory_size{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request cache hit",
     "type": "graph",
     "description": "Request cache hit count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_request_cache_hit_count{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request cache evictions",
     "type": "graph",
     "description": "Request cache evictions\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_query_cache_evictions{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request cache miss",
     "type": "graph",
     "description": "Request cache miss count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_nodes_request_cache_miss_count{cluster=~\"$cluster\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Nodes: /_cat/nodes segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Segments counts",
   "type": "graph",
   "description": "Number of segments\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_cat_nodes_segments_count{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments version map memory",
   "type": "graph",
   "description": "Memory used by version map\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_segments_version_map_memory_bytes{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory used by index writer",
   "type": "graph",
   "description": "Memory used by index writer\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_segments_index_writer_memory_bytes{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory used by fixed bitset",
   "type": "graph",
   "description": "Memory used by fixed bit sets for nested object field types\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_segments_fixed_bitset_memory_bytes{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments memory",
   "type": "graph",
   "description": "Memory used by segments\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_cat_nodes_segments_memory_bytes{cluster=~\"$cluster\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}