{
 "title": "Elasticsearch Exporter: general",
 "tags": [
  "elasticsearch",
  "cpu",
  "cache",
  "indices",
  "nodes",
  "system",
  "thread pool"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count(elasticsearch_cluster_health_number_of_nodes) by (cluster))"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "query_result(increase(elasticsearch_cat_indices_segments_memory_bytes{cluster=\"$cluster\"}[${__range_s}s]) > 0)"
    }
   },
   {
    "name": "thread_pool_queue_search",
    "query": {
     "query": "query_result(topk($topk,sum(increase(elasticsearch_cat_thread_pool_queue{cluster=\"$cluster\", name=~\"search\"}[${__range_s}s])) by (node_name) ))"
    }
   },
   { "name": "topk", "query": "3,5,10,20" },
   {
    "name": "thread_pool_queue_write",
    "query": {
     "query": "query_result(topk($topk,sum(increase(elasticsearch_cat_thread_pool_queue{cluster=\"$cluster\", name=~\"write\"}[${__range_s}s])) by (node_name) ))"
    }
   },
   { "name": "min_interval", "query": "15s,30s,45s,60s" }
  ]
 },
 "panels": [
  {
   "title": "Cluster health: /_cluster/health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch nodes count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})",
       "legendFormat": "total nodes"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})",
       "legendFormat": "data nodes"
      }
     ]
    },
    {
     "title": "Shards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Elasticsearch shards count" }
     ],
     "targets": [
      {
       "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})",
       "legendFormat": "Active shards"
      },
      {
       "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"})",
       "legendFormat": "Primary shards"
      },
      {
       "expr": " min(elasticsearch_cluster_health_active_shards_percent_as_number{cluster=\"$cluster\"})",
       "legendFormat": "% Active shards"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pool main: /_cat/thread_pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Thread pool: queue",
   "type": "graph",
   "description": "Number of tasks in the queue for the current thread pool.\n\nHigh queue indicates that requests are \"waiting\" in line to be executed. In best circumstances queue should be close to zero. Elasticsearch imposes limit on the queue capacity, after capacity is reached, requests in queue will be rejected.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Threads count" }
   ],
   "targets": [
    {
     "expr": "sum(max(increase(elasticsearch_cat_thread_pool_queue{cluster=\"$cluster\"}[$time])) by (node_name, name)) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(elasticsearch_cat_thread_pool_queue{cluster=\"$cluster\", name=~\"search\", node_name=~\"$thread_pool_queue_search\"}) by (node_name)",
     "legendFormat": "search: {{node_name}}"
    },
    {
     "expr": "max(elasticsearch_cat_thread_pool_queue{cluster=\"$cluster\", name=~\"write\", node_name=~\"$thread_pool_queue_write\"}) by (node_name)",
     "legendFormat": "write: {{node_name}}"
    }
   ]
  },
  {
   "title": "Thread pool: active",
   "type": "graph",
   "description": "Number of active threads in the current thread pool.\n\nActive threads \"working\" in Elasticsearch cluster. Graph show total main threads \"search\" and \"write\" compared to currently active threads.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Active threads in pool" }
   ],
   "targets": [
    {
     "expr": "sum(max(elasticsearch_cat_thread_pool_active{cluster=\"$cluster\"}) by (node_name, name)) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(max(elasticsearch_cat_thread_pool_pool_size{cluster=\"$cluster\", name=~\"write\"}) by (node_name))",
     "legendFormat": "Total: write"
    },
    {
     "expr": "sum(max(elasticsearch_cat_thread_pool_pool_size{cluster=\"$cluster\", name=~\"search\"}) by (node_name))",
     "legendFormat": "Total: search"
    }
   ]
  },
  {
   "title": "Thread pool: rejected",
   "type": "graph",
   "description": "Number of rejected threads in the current thread pool.\n\nRejected threads happen when cluster is \"overloaded\" usually when Elasticsearch thread pool queue capacity is reached. When cluster queue capacity is reached Elasticsearch will start rejecting requests to protect cluster from complete outage.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Active threads in pool" }
   ],
   "targets": [
    {
     "expr": "sum(increase(elasticsearch_cat_thread_pool_rejected{cluster=\"$cluster\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread pool limits: /_cat/thread_pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread pool: size",
     "type": "graph",
     "description": "Configured fixed number of active threads allowed in the current thread pool.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Threads count per pool" }
     ],
     "targets": [
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_pool_size{cluster=\"$cluster\"}) by (node_name, name)) by (name) ",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_pool_size{cluster=\"$cluster\"}) by (node_name, name))",
       "legendFormat": "Total size"
      }
     ]
    },
    {
     "title": "Thread pool: core",
     "type": "graph",
     "description": "Configured core number of active threads allowed in the current thread pool.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Threads count" }
     ],
     "targets": [
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_core{cluster=\"$cluster\"}) by (node_name, name)) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread pool: largest",
     "type": "graph",
     "description": "Highest number of active threads in the current thread pool.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Threads count" }
     ],
     "targets": [
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_largest{cluster=\"$cluster\"}) by (node_name, name)) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread pool: completed",
     "type": "graph",
     "description": "Number of completed tasks\n\nCompleted thread pool \"tasks\" is useful information about thread trends. This graph indicates current throughput of per thread type in operations per minute.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#scaling-thread-pool",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "opm", "label": "Tasks" }
     ],
     "targets": [
      {
       "expr": "sum(max(irate(elasticsearch_cat_thread_pool_completed{cluster=\"$cluster\"}[$time])) by (node_name, name)) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread pool: queue size",
     "type": "graph",
     "description": "Number of tasks in the queue for the current thread pool.\n\nCurrent queue size in Elasticsearch cluster per thread type.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Threads count" }
     ],
     "targets": [
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_queue_size{cluster=\"$cluster\"}) by (node_name, name)) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread pool: max",
     "type": "graph",
     "description": "Configured maximum number of active threads allowed in the current thread pool.\n\nMaximum number of recorded threads per type in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html#cat-thread-pool-query-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Threads count" }
     ],
     "targets": [
      {
       "expr": "sum(max(elasticsearch_cat_thread_pool_max{cluster=\"$cluster\"}) by (node_name, name)) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/nodes cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request cache hit ratio",
     "type": "graph",
     "description": "Request cache hit ratio calculated by hits / (hits + miss). Cache hit ratio is expressed in percentage.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit", "label": "Hit ratio" }
     ],
     "targets": [
      {
       "expr": "min(increase(elasticsearch_cat_indices_request_cache_hit_count{cluster=\"$cluster\", index=~\"$index\"}[$time]) / (increase(elasticsearch_cat_indices_request_cache_hit_count{cluster=\"$cluster\", index=~\"$index\"}[$time]) + increase(elasticsearch_cat_indices_request_cache_miss_count{cluster=\"$cluster\", index=~\"$index\"}[$time]))) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Request cache memory",
     "type": "graph",
     "description": "Used request cache memory in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_request_cache_memory_size{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Request cache evictions",
     "type": "graph",
     "description": "Request cache evictions. Cluster might not have evictions if refresh interval happens frequently and/or cluster has enough memory to cache all requests before starting evicting the cache.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "opm", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_request_cache_evictions{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Request cache hit",
     "type": "graph",
     "description": "Request cache hit count\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "opm", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_request_cache_hit_count{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Request cache miss",
     "type": "graph",
     "description": "Request cache miss count\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 4 },
     "yaxes": [
      { "format": "opm", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_request_cache_miss_count{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Query cache memory",
     "type": "graph",
     "description": "Used query cache memory in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_query_cache_memory_size{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "description": "Query cache evictions. Cluster might not have evictions if refresh interval happens frequently and/or cluster has enough memory to cache all requests before starting evicting the cache.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "opm", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_query_cache_evictions{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices index query, fetch refresh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index query: current",
     "type": "graph",
     "description": "Current query phase operations per second.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_search_query_current{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index fetch: current",
     "type": "graph",
     "description": "Current fetch phase operations per second.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ops", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_search_fetch_current{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index refreshing time",
     "type": "graph",
     "description": "Time spent in refresh operations in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_refresh_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_indexing_index_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index query time",
     "type": "graph",
     "description": "Time spent in query phase in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_search_query_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_search_query_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index fetch time",
     "type": "graph",
     "description": "Time spent in fetch phase in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_search_fetch_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_search_fetch_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index total refreshes",
     "type": "graph",
     "description": "Number of total refresh counts in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_refresh_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index total query",
     "type": "graph",
     "description": "Total query phase operations per second.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_search_query_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index total fetch",
     "type": "graph",
     "description": "Total fetch operations per second in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_search_fetch_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices documents, flushes & field data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total documents",
     "type": "graph",
     "description": "Available document in the Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_docs_count{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Deleted documents",
     "type": "graph",
     "description": "Deleted documents in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_docs_deleted{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Flushed document flush time",
     "type": "graph",
     "description": "Total time spent performing flush operations. Flush is operation of writing data back to disk.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_flush_total_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_flush_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Field data size",
     "type": "graph",
     "description": "The field data cache contains field data and global ordinals, which are both used to support aggregations on certain field types. Since these are on-heap data structures, it is important to monitor the cache’s use.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-fielddata.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_fielddata_memory_size{cluster=\"$cluster\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Number of flushes",
     "type": "graph",
     "description": "Number of times index was flushed. Flush is operation of writing data back to disk.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_flush_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices settings & misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index primaries",
     "type": "graph",
     "description": "Total index primary shards per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_pri{cluster=\"$cluster\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index Replicas",
     "type": "graph",
     "description": "Total index replica shards per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_rep{cluster=\"$cluster\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Open contexts",
     "type": "graph",
     "description": "Open search contexts in Elasticsearch cluster. Search context is the state that is maintained for the duration of a search operation on a shard. The more concurrent search operations you have the more search context objects are active at any one time.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_search_open_contexts{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index indexing time",
     "type": "graph",
     "description": "Time spent in indexing operations.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_indexing_index_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_indexing_index_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing operations: current",
     "type": "graph",
     "description": "Number of current indexing operations per second in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "opm", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_indexing_index_current{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing failed documents",
     "type": "graph",
     "description": "Number of failed indexing operations per second in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_indices_indexing_index_failed{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Deleted document deletion time",
     "type": "graph",
     "description": "Time spent to delete documents in seconds. Deleted documents are not removed instantly. Deleted documents are deleted after cluster refresh happens on each index shard per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_indexing_delete_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_indexing_delete_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing total documents",
     "type": "graph",
     "description": "Number of indexed documents per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_indexing_index_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexing deleted documents",
     "type": "graph",
     "description": "Number of current deletions in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_indexing_delete_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices memory & merging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index memory total",
     "type": "graph",
     "description": "Total used memory for indexing operations per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_memory_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index merges: current",
     "type": "graph",
     "description": "Number of current merges per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_merges_current{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Merges total",
     "type": "graph",
     "description": "Number of completed merge operations per second per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "opm", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_merges_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Merged total size",
     "type": "graph",
     "description": "Size merged of documents per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_cat_indices_merges_total_size{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: /_cat/indices segments, warmer & store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index segments count",
     "type": "graph",
     "description": "Number of total segments per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_segments_count{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Warmer time",
     "type": "graph",
     "description": "Time spent in warmers per index. Some data in the index needs to be loaded into memory for fast access to the index. Since this loading is sometimes lazy, warmers are run just before a new segment gets published in order to ensure that following requests won't need to load this data as part of the query execution. The two main things that warmers load into memory are norms (used for scoring) and field data (used for sorting and facets/aggregations).\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_warmer_total_time_seconds{cluster=\"$cluster\", index=~\"$index\"}[$time]) / increase(elasticsearch_cat_indices_warmer_total{cluster=\"$cluster\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments memory",
     "type": "graph",
     "description": "Total memory used by segments per index. \nEach shard contains multiple \"segments\", where a segment is an inverted index. A search in a shard will search each segment in turn, then combine their results into the final results for that shard.\n\nWhile you are indexing documents, Elasticsearch collects them in memory (and in the transaction log, for safety) then every second or so, writes a new small segment to disk, and \"refreshes\" the search.\n\nThis makes the data in the new segment visible to search (ie they are \"searchable\"), but the segment has not been fsync'ed to disk, so is still at risk of data loss.\n\nEvery so often, Elasticsearch will \"flush\", which means fsync'ing the segments, (they are now \"committed\") and clearing out the transaction log, which is no longer needed because we know that the new data has been written to disk.\n\nThe more segments there are, the longer each search takes. So Elasticsearch will merge a number of segments of a similar size (\"tier\") into a single bigger segment, through a background merge process. Once the new bigger segment is written, the old segments are dropped. This process is repeated on the bigger segments when there are too many of the same size.\n\nSegments are immutable. When a document is updated, it actually just marks the old document as deleted, and indexes a new document. The merge process also expunges these old deleted documents.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_segments_memory_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments version map memory",
     "type": "graph",
     "description": "Total memory used by version map per index. Each shard contains multiple \"segments\", where a segment is an inverted index. A search in a shard will search each segment in turn, then combine their results into the final results for that shard.\n\nWhile you are indexing documents, Elasticsearch collects them in memory (and in the transaction log, for safety) then every second or so, writes a new small segment to disk, and \"refreshes\" the search.\n\nThis makes the data in the new segment visible to search (ie they are \"searchable\"), but the segment has not been fsync'ed to disk, so is still at risk of data loss.\n\nEvery so often, Elasticsearch will \"flush\", which means fsync'ing the segments, (they are now \"committed\") and clearing out the transaction log, which is no longer needed because we know that the new data has been written to disk.\n\nThe more segments there are, the longer each search takes. So Elasticsearch will merge a number of segments of a similar size (\"tier\") into a single bigger segment, through a background merge process. Once the new bigger segment is written, the old segments are dropped. This process is repeated on the bigger segments when there are too many of the same size.\n\nSegments are immutable. When a document is updated, it actually just marks the old document as deleted, and indexes a new document. The merge process also expunges these old deleted documents.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_segments_version_map_memory_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Warmer total",
     "type": "graph",
     "description": "Total warmer operations in second. Some data in the index needs to be loaded into memory for fast access to the index. Since this loading is sometimes lazy, warmers are run just before a new segment gets published in order to ensure that following requests won't need to load this data as part of the query execution. The two main things that warmers load into memory are norms (used for scoring) and field data (used for sorting and facets/aggregations).\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_cat_indices_warmer_total{cluster=\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Store size",
     "type": "graph",
     "description": "Total storage size of primaries & replicas per index in Elasticsearch cluster.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_store_size{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments fixed bitset memory",
     "type": "graph",
     "description": "Memory used by fixed bit sets per index. Each shard contains multiple \"segments\", where a segment is an inverted index. A search in a shard will search each segment in turn, then combine their results into the final results for that shard.\n\nWhile you are indexing documents, Elasticsearch collects them in memory (and in the transaction log, for safety) then every second or so, writes a new small segment to disk, and \"refreshes\" the search.\n\nThis makes the data in the new segment visible to search (ie they are \"searchable\"), but the segment has not been fsync'ed to disk, so is still at risk of data loss.\n\nEvery so often, Elasticsearch will \"flush\", which means fsync'ing the segments, (they are now \"committed\") and clearing out the transaction log, which is no longer needed because we know that the new data has been written to disk.\n\nThe more segments there are, the longer each search takes. So Elasticsearch will merge a number of segments of a similar size (\"tier\") into a single bigger segment, through a background merge process. Once the new bigger segment is written, the old segments are dropped. This process is repeated on the bigger segments when there are too many of the same size.\n\nSegments are immutable. When a document is updated, it actually just marks the old document as deleted, and indexes a new document. The merge process also expunges these old deleted documents.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_segments_fixed_bitset_memory_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments index writer memory",
     "type": "graph",
     "description": "Memory used by index writer per index. Each shard contains multiple \"segments\", where a segment is an inverted index. A search in a shard will search each segment in turn, then combine their results into the final results for that shard.\n\nWhile you are indexing documents, Elasticsearch collects them in memory (and in the transaction log, for safety) then every second or so, writes a new small segment to disk, and \"refreshes\" the search.\n\nThis makes the data in the new segment visible to search (ie they are \"searchable\"), but the segment has not been fsync'ed to disk, so is still at risk of data loss.\n\nEvery so often, Elasticsearch will \"flush\", which means fsync'ing the segments, (they are now \"committed\") and clearing out the transaction log, which is no longer needed because we know that the new data has been written to disk.\n\nThe more segments there are, the longer each search takes. So Elasticsearch will merge a number of segments of a similar size (\"tier\") into a single bigger segment, through a background merge process. Once the new bigger segment is written, the old segments are dropped. This process is repeated on the bigger segments when there are too many of the same size.\n\nSegments are immutable. When a document is updated, it actually just marks the old document as deleted, and indexes a new document. The merge process also expunges these old deleted documents.\n\nDocs: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_cat_indices_segments_index_writer_memory_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}