{
 "title": "Elasticsearch Exporter: /_nodes/stats",
 "description": "Returns cluster nodes statistics",
 "tags": [
  "elasticsearch",
  "cpu",
  "cache",
  "jvm",
  "segments",
  "translog",
  "documents",
  "breakers",
  "indexing"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(elasticsearch_nodes_stats_indices_docs_count{cluster=~\"$cluster\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operating system CPU usage",
   "type": "graph",
   "description": "/_nodes/stats OS cpu percent\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent usage" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_os_cpu_percent{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "description": "/_nodes/stats OS CPU process percent\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent usage" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_process_cpu_percent{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(elasticsearch_nodes_stats_process_cpu_percent{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "description": "/_nodes/stats OS cpu percent\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent usage" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_os_mem_free_percent{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(elasticsearch_nodes_stats_os_mem_free_percent{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "description": "/_nodes/stats OS cpu percent\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent usage" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_os_mem_used_percent{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(elasticsearch_nodes_stats_os_mem_used_percent{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Transport receive/transmit bytes",
   "type": "graph",
   "description": "/_nodes/stats transport receive/transmit size in bytes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max(irate(elasticsearch_nodes_stats_transport_rx_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(max(irate(elasticsearch_nodes_stats_transport_tx_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Transport receive/transmit count",
   "type": "graph",
   "description": "/_nodes/stats transport receive/transmit\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(max(irate(elasticsearch_nodes_stats_transport_rx_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(max(irate(elasticsearch_nodes_stats_transport_tx_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Transport server open",
   "type": "graph",
   "description": "/_nodes/stats transport server open\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_transport_server_open{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster health: /_cluster/health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Elasticsearch nodes count" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})",
     "legendFormat": "total nodes"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})",
     "legendFormat": "data nodes"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Elasticsearch shards count" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Active shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Primary shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards_percent_as_number{cluster=~\"$cluster\"})",
     "legendFormat": "% Active shards"
    }
   ]
  },
  { "title": "Query & fetch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Query time",
   "type": "graph",
   "description": "/_nodes/stats time querying\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_nodes_stats_indices_search_query_time_in_seconds{cluster=~\"$cluster\"}[$__rate_interval]) / rate(elasticsearch_nodes_stats_indices_search_query_total{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query current",
   "type": "graph",
   "description": "/_nodes/stats indices query current\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_search_query_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search open contexts",
   "type": "graph",
   "description": "/_nodes/stats indices search open contexts\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_search_open_contexts{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch time",
   "type": "graph",
   "description": "/_nodes/stats time fetching\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_nodes_stats_indices_search_fetch_time_in_seconds{cluster=~\"$cluster\"}[$__rate_interval]) / rate(elasticsearch_nodes_stats_indices_search_fetch_total{cluster=~\"$cluster\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch current",
   "type": "graph",
   "description": "/_nodes/stats indices fetch current\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_search_fetch_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads count",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_threads_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Threads peak count",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_threads_peak_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GC young collect time",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_jvm_gc_collectors_young_collection_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_jvm_gc_collectors_young_collection_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GC old collect time",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_jvm_gc_collectors_old_collection_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_jvm_gc_collectors_old_collection_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools direct count",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_direct_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools mapped count",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_mapped_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools HEAP percent used",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "percent", "label": "Percent usage" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_heap_used_percent{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "avg(elasticsearch_nodes_stats_jvm_mem_heap_used_percent{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "Buffer pools HEAP committed/used/max",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_heap_committed_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "committed: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_heap_max_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "max: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_heap_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "used: {{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools direct used capacity",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_direct_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools mapped used capacity",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_mapped_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools mapped used capacity",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_mapped_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools non HEAP committed/used",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_non_heap_committed_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "committed: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_non_heap_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "used: {{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools direct total capacity",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_direct_total_capacity_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools mapped total capacity",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_buffer_pools_mapped_total_capacity_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools survivor peak used/used",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_survivor_peak_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "survivor peak used: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_survivor_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "survivor used: {{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools young peak used/used",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_young_peak_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "young peak used: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_young_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "young used: {{name}}"
      }
     ]
    },
    {
     "title": "Buffer pools old max/peak max/peak used/old used",
     "type": "graph",
     "description": "/_nodes/stats JVM\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_old_max_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "old max: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_old_peak_max_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "old peak max: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_old_peak_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "old peak used: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_jvm_mem_pools_old_used_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "old used: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices request cache hit ratio",
     "type": "graph",
     "description": "/_nodes/stats indices request cache hit ratio derived from hit / (hit + miss)\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit", "label": "Hit ratio" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_request_cache_hit_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / (max(rate(elasticsearch_nodes_stats_indices_request_cache_hit_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) + max(rate(elasticsearch_nodes_stats_indices_request_cache_miss_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices request cache memory size",
     "type": "graph",
     "description": "/_nodes/stats indices request cache memory size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_request_cache_memory_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices query cache hit ratio",
     "type": "graph",
     "description": "/_nodes/stats indices query cache hit ratio derived from hit / (hit + miss)\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit", "label": "Hit ratio" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_query_cache_hit_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / (max(rate(elasticsearch_nodes_stats_indices_query_cache_hit_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) + max(rate(elasticsearch_nodes_stats_indices_query_cache_miss_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache size",
     "type": "graph",
     "description": "/_nodes/stats indices query cache size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_query_cache_cache_size{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache count",
     "type": "graph",
     "description": "/_nodes/stats indices query cache count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indices_query_cache_cache_count{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache total count",
     "type": "graph",
     "description": "/_nodes/stats indices query cache total count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_query_cache_total_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache miss count",
     "type": "graph",
     "description": "/_nodes/stats indices query cache miss count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_query_cache_miss_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache memory size",
     "type": "graph",
     "description": "/_nodes/stats indices query cache memory size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_query_cache_memory_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache evictions",
     "type": "graph",
     "description": "/_nodes/stats indices query cache evictions\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indices_query_cache_evictions{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices query cache miss count",
     "type": "graph",
     "description": "/_nodes/stats indices query cache miss count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_query_cache_miss_count{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexing pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current all memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure current memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_current_all_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current combined primary memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure current combined\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_current_combined_coordinating_and_primary_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current coordinating memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure current coordinating\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_current_coordinating_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current primary memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure current primary\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_current_primary_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total primary memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure total primary\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_total_primary_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total all memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure total memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_total_all_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total combined primary memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure total combined\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_total_combined_coordinating_and_primary_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total coordinating memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure total coordinating\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_total_coordinating_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current replica memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure current replica\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_current_replica_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total replica memory",
     "type": "graph",
     "description": "Nodes stats indexing pressure total replica\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_nodes_stats_indexing_pressure_memory_total_replica_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merges current",
     "type": "graph",
     "description": "/_nodes/stats indices merges current\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_merges_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merged documents",
     "type": "graph",
     "description": "/_nodes/stats merged current documents\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_current_docs{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merged documents size",
     "type": "graph",
     "description": "/_nodes/stats merges current size in bytes\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_current_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merge time",
     "type": "graph",
     "description": "/_nodes/stats time merging\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_total_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_indices_merges_total{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges auto throttle",
     "type": "graph",
     "description": "/_nodes/stats merges total throttle\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_total_auto_throttle_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges total documents",
     "type": "graph",
     "description": "/_nodes/stats total documents merges\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_total_docs{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merges total size",
     "type": "graph",
     "description": "/_nodes/stats merges total size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_total_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merge throttled time",
     "type": "graph",
     "description": "/_nodes/stats time merging was throttled\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_merges_total_throttled_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Documents count & indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Indices documents count",
   "type": "graph",
   "description": "/_nodes/stats indices documents count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_docs_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing index total",
   "type": "graph",
   "description": "/_nodes/stats indices indexing index total\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_nodes_stats_indices_indexing_index_total{cluster=~\"$cluster\", name=~\"$name\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing index current",
   "type": "graph",
   "description": "/_nodes/stats indices indexing index current\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_indexing_index_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing index time",
   "type": "graph",
   "description": "/_nodes/stats time spent indexing\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_indexing_index_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}) by (name) / max(elasticsearch_nodes_stats_indices_indexing_index_total{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indices documents deleted count",
   "type": "graph",
   "description": "/_nodes/stats indices deleted documents count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_docs_deleted{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing delete current",
   "type": "graph",
   "description": "/_nodes/stats indices indexing delete current\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_indexing_delete_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing index failed",
   "type": "graph",
   "description": "/_nodes/stats indices indexing index failed\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_indexing_index_current{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing delete time",
   "type": "graph",
   "description": "/_nodes/stats time spent deleting\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_stats_indices_indexing_delete_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}) by (name) / max(elasticsearch_nodes_stats_indices_indexing_delete_total{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indices store & misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices store size",
     "type": "graph",
     "description": "/_nodes/stats indices store size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_store_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fielddata memory size",
     "type": "graph",
     "description": "Nodes stats indices fielddata memory size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_fielddata_memory_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indices recovery throttle",
     "type": "graph",
     "description": "/_nodes/stats indices recovery throttle time\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_recovery_throttle_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices refresh, warmer & flush",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flush time",
     "type": "graph",
     "description": "/_nodes/stats time spent flushing\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_flush_total_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_indices_flush_total{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Refresh time",
     "type": "graph",
     "description": "/_nodes/stats time refreshing\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_refresh_total_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_indices_refresh_total{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Warmer time",
     "type": "graph",
     "description": "/_nodes/stats time warming\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_warmer_total_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_indices_warmer_total{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Flushing periodic/total",
     "type": "graph",
     "description": "/_nodes/stats indices flush period\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_flush_periodic{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "periodic: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_indices_flush_total{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "total: {{name}}"
      }
     ]
    },
    {
     "title": "Refresh external time",
     "type": "graph",
     "description": "/_nodes/stats time in external refresh\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_refresh_external_total_time_in_seconds{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name) / max(rate(elasticsearch_nodes_stats_indices_refresh_external_total{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parent estimated size",
     "type": "graph",
     "description": "/_nodes/stats parent estimated breakers size. Parent-level breaker that specifies the total amount of memory that can be used across all breakers. \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_parent_estimated_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "estimated {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_parent_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "limit {{name}}"
      }
     ]
    },
    {
     "title": "Request estimated size",
     "type": "graph",
     "description": "/_nodes/stats request estimated breakers size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_request_estimated_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "In flight requests estimated size",
     "type": "graph",
     "description": "/_nodes/stats in flight requests estimated breakers size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_in_flight_requests_estimated_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fielddata estimated size",
     "type": "graph",
     "description": "/_nodes/stats fielddata estimated breakers size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_fielddata_estimated_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Accounting estimated size",
     "type": "graph",
     "description": "/_nodes/stats accounting estimated breakers size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_accounting_estimated_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Model inference limit size",
     "type": "graph",
     "description": "/_nodes/stats model inference limit size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_model_inference_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parent limit size",
     "type": "graph",
     "description": "/_nodes/stats parent breakers limit size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_parent_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request limit size",
     "type": "graph",
     "description": "/_nodes/stats request breakers limit size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_request_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "In fllight requests limit size",
     "type": "graph",
     "description": "/_nodes/stats in flight requests limit size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_in_flight_requests_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fielddata limit size",
     "type": "graph",
     "description": "/_nodes/stats fielddata limit size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_fielddata_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Accounting limit size",
     "type": "graph",
     "description": "/_nodes/stats accounting limit size \n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_breakers_accounting_limit_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations",
     "type": "graph",
     "description": "/_nodes/stats indices translog operations\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_translog_operations{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Translog uncommitted operations",
     "type": "graph",
     "description": "/_nodes/stats indices translog uncommitted operations\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_nodes_stats_indices_translog_uncommitted_operations{cluster=~\"$cluster\", name=~\"$name\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Translog size in bytes",
     "type": "graph",
     "description": "/_nodes/stats indices translog size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_translog_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Translog uncommittedsize in bytes",
     "type": "graph",
     "description": "/_nodes/stats indices translog uncommitted size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_translog_uncommitted_size_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments count",
     "type": "graph",
     "description": "/_nodes/stats segments count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_count{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Terms memory",
     "type": "graph",
     "description": "/_nodes/stats terms memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_terms_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segments document values memory",
     "type": "graph",
     "description": "/_nodes/stats segments documents values memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_doc_values_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segments index writer memory",
     "type": "graph",
     "description": "/_nodes/stats segments index writer memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_index_writer_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segments memory",
     "type": "graph",
     "description": "/_nodes/stats segments memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Stored fields memory",
     "type": "graph",
     "description": "/_nodes/stats stored fields memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_stored_fields_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segments norms memory",
     "type": "graph",
     "description": "/_nodes/stats segments norms memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_norms_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Version map memory",
     "type": "graph",
     "description": "/_nodes/stats version map memory\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_stats_indices_segments_version_map_memory_in_bytes{cluster=~\"$cluster\", name=~\"$name\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}