{
 "title": "Elasticsearch Exporter: /_nodes/info",
 "description": "Returns cluster nodes information.",
 "tags": [
  "elasticsearch",
  "nodes",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(elasticsearch_nodes_info_thread_pool_search_size{cluster=~\"$cluster\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes /_nodes/info thread pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search pool size",
   "type": "table",
   "description": "Thread pool search size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_search_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Generic pool core",
   "type": "table",
   "description": "Thread pool generic\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_generic_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Warmer pool core",
   "type": "table",
   "description": "Thread pool warmer\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_warmer_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Flush pool core",
   "type": "table",
   "description": "Thread pool flush core size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_flush_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Get pool size",
   "type": "table",
   "description": "Thread pool get size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_get_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write pool size",
   "type": "table",
   "description": "Thread pool write size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_write_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search queue size",
   "type": "table",
   "description": "Thread pool queue size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_search_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Generic pool max",
   "type": "table",
   "description": "Thread pool generic\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_generic_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Warmer pool max",
   "type": "table",
   "description": "Thread pool warmer\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_warmer_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Flush pool max",
   "type": "table",
   "description": "Thread pool flush max size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_flush_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Get queue size",
   "type": "table",
   "description": "Thread pool get size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_get_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write queue size",
   "type": "table",
   "description": "Thread pool write size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_write_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search throttled pool size",
   "type": "table",
   "description": "Thread pool throttled pool size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_search_throttled_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Generic queue size",
   "type": "table",
   "description": "Thread pool get size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_generic_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Warmer queue size",
   "type": "table",
   "description": "Thread pool warmer size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_warmer_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Flush queue size",
   "type": "table",
   "description": "Thread pool flush size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_flush_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search throttled queue size",
   "type": "table",
   "description": "Thread pool throttled queue size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_search_throttled_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes /_nodes/info thread pool misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Management pool core",
   "type": "table",
   "description": "Thread pool management\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_management_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Refresh pool core",
   "type": "table",
   "description": "Thread pool refresh\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_refresh_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard started pool core",
   "type": "table",
   "description": "Thread pool fetch shard started\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_fetch_shard_started_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard store pool core",
   "type": "table",
   "description": "Thread pool fetch shard store\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_fetch_shard_store_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Snapshot pool core",
   "type": "table",
   "description": "Thread pool snapshot core\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_snapshot_core{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Listener pool size",
   "type": "table",
   "description": "Thread pool listener size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_listener_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Managment pool max",
   "type": "table",
   "description": "Thread pool managment\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_management_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Refresh pool max",
   "type": "table",
   "description": "Thread pool refresh\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_refresh_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard started pool max",
   "type": "table",
   "description": "Thread pool fetch shard started\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_refresh_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard store pool max",
   "type": "table",
   "description": "Thread pool fetch shard store\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_fetch_shard_store_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Snapshot pool max",
   "type": "table",
   "description": "Thread pool snapshot max\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_snapshot_max{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Listener queue size",
   "type": "table",
   "description": "Thread pool listener queue size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_listener_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Management queue size",
   "type": "table",
   "description": "Thread pool management size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_management_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Refresh queue size",
   "type": "table",
   "description": "Thread pool refresh size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_refresh_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard started queue size",
   "type": "table",
   "description": "Thread pool fetch shard started\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_refresh_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetch shard store queue size",
   "type": "table",
   "description": "Thread pool fetch shard store\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_fetch_shard_store_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Snapshot queue size",
   "type": "table",
   "description": "Thread pool snapshot queue size\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(elasticsearch_nodes_info_thread_pool_snapshot_queue_size{cluster=~\"$cluster\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes /_nodes/info: JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory non HEAP initial",
     "type": "graph",
     "description": "JVM memory non HEAP initial/max\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_info_jvm_mem_non_heap_init_in_bytes{cluster=~\"$cluster\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "HEAP memory initial/max",
     "type": "graph",
     "description": "JVM memory HEAP initial/max\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-path-params",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_nodes_info_jvm_mem_heap_init_in_bytes{cluster=~\"$cluster\"}) by (name)",
       "legendFormat": "initial: {{name}}"
      },
      {
       "expr": "max(elasticsearch_nodes_info_jvm_mem_heap_max_in_bytes{cluster=~\"$cluster\"}) by (name)",
       "legendFormat": "max: {{name}}"
      }
     ]
    }
   ]
  }
 ]
}