{
 "title": "Elasticsearch Exporter: /_nodes/usage",
 "description": "Returns information on the usage of features.",
 "tags": [
  "elasticsearch",
  "nodes",
  "system",
  "distribution"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(elasticsearch_nodes_usage_rest_actions_main_action{cluster=~\"$cluster\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes /_nodes/usage main actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Search action",
   "type": "graph",
   "description": "Rest action: search\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-usage.html",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_search_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bulk action",
   "type": "graph",
   "description": "Rest action: bulk\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-usage.html",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_bulk_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Count action",
   "type": "graph",
   "description": "Rest action: count\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-usage.html",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_count_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes /_nodes/usage: aggregations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Aggregations terms",
   "type": "graph",
   "description": "Nodes usage: aggregation terms\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-usage.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_aggregations_terms_bytes{cluster=~\"$cluster\", name=~\"$name\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Aggregations top hits other",
   "type": "graph",
   "description": "Top hits other\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-top-hits-aggregation.html#search-aggregations-metrics-top-hits-aggregation",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_aggregations_top_hits_other{cluster=~\"$cluster\", name=~\"$name\"}[$time])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes /_nodes/usage rest actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Rest actions",
   "type": "graph",
   "description": "Rest actions\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-usage.html",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_alias_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/alias: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_allocation_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/allocation: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_fielddata_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/fielddata: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_indices_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/indices: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_nodes_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/nodes: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_recovery_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/recovery: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_shards_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/shards: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_templates_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/templates: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cat_threadpool_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cat/thread_pool: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cluster_allocation_explain_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cluster/allocation/explain: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cluster_get_settings_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "get cluster settings: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cluster_health_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_cluster/health: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cluster_reroute_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "cluster reroute: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_create_index_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "create index: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_cluster_update_settings_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "cluster update settings: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_delete_index_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "delete index: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_force_merge_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "force merge: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_get_aliases_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "get aliases: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_get_index_template_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "get index template: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_get_indices_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "get indices: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_indices_stats_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "indices stats: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_ingest_get_pipeline_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "get pipeline action: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_ingest_put_pipeline_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "put pipeline action: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_msearch_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_msearch: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_nodes_info_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_nodes/info: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_nodes_stats_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_nodes/stats: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_nodes_usage_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_nodes/usage: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_put_index_template_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "put index template: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_refresh_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "/_refresh: {{name}}"
    },
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_update_settings_action{cluster=~\"$cluster\"}[$time])) by (name)",
     "legendFormat": "update settings: {{name}}"
    }
   ]
  },
  {
   "title": "Main action",
   "type": "graph",
   "description": "Main rest action\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-usage.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_nodes_usage_rest_actions_main_action{cluster=~\"$cluster\"}[$time]) > 0) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}