{
 "title": "Elasticsearch Exporter: /self metrics",
 "tags": [
  "elasticsearch",
  "exporter",
  "system"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape time per subsystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "In seconds" }
   ],
   "targets": [
    {
     "expr": "avg(rate(elasticsearch_subsystem_request_duration_seconds_sum{cluster=~\"$cluster\"}[$time]) / rate(elasticsearch_subsystem_request_duration_seconds_count{cluster=~\"$cluster\"}[$time])) by (subsystem)",
     "legendFormat": "{{subsystem}}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=\"elasticsearch-exporter2\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes{job=\"elasticsearch-exporter2\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}