{
 "title": "Elasticsearch Exporter: /_stats",
 "description": "Returns statistics for one or more indices. For data streams, the API retrieves statistics for the stream’s backing indices.",
 "tags": [
  "elaticsearch",
  "system",
  "cpu",
  "cache",
  "segments"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_stats_total_docs_count, cluster)"
    }
   },
   {
    "name": "time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "index",
    "query": {
     "query": "query_result(increase(elasticsearch_stats_total_store_size_in_bytes{cluster=~\"$cluster\"}[${__range_s}s]) > 0)\n\n"
    }
   },
   { "name": "min_interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "Request cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request cache hit ratio",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_request_cache_hit_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index) / (max(rate(elasticsearch_stats_total_request_cache_hit_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index) + max(rate(elasticsearch_stats_total_request_cache_miss_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index))",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Request cache hit count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_request_cache_hit_count{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Request cache memory size",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_stats_total_request_cache_memory_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
     "legendFormat": "index {{index}}"
    },
    {
     "expr": "sum(max(elasticsearch_stats_total_request_cache_memory_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request cache miss count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_request_cache_miss_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  { "title": "Query cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Query cache hit ratio",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_query_cache_hit_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index) / max(rate(elasticsearch_stats_total_query_cache_total_count{cluster=~\"$cluster\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache hit count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_query_cache_hit_count{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache total count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_query_cache_total_count{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache memory size",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_stats_total_query_cache_memory_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
     "legendFormat": "index {{index}}"
    },
    {
     "expr": "sum(max(elasticsearch_stats_total_query_cache_memory_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query cache miss count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_query_cache_miss_count{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache count",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_stats_total_query_cache_cache_count{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Size in bytes" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_stats_total_query_cache_cache_size{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_stats_total_query_cache_evictions{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  { "title": "Search ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Query time",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_search_query_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "Query total",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_stats_total_search_query_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Query current",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_stats_total_search_query_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "Open contexts",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_stats_total_search_open_contexts{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Fetches time",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s", "label": "Time spent" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_stats_total_search_fetch_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "Fetches total",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(increase(elasticsearch_stats_total_search_fetch_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
     "legendFormat": "index {{index}}"
    }
   ]
  },
  {
   "title": "Fetches current",
   "type": "graph",
   "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_stats_total_search_fetch_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_indexing_index_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Indexing index time",
     "type": "graph",
     "description": "The total amount of time spend on executing index operations.\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_indexing_index_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Indexing delete total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_indexing_delete_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Indexing delete time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_indexing_delete_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Indexing current",
     "type": "graph",
     "description": "Returns the currently in-flight indexing operations.\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_indexing_index_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Indexing failed",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_indexing_index_failed{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Indexing delete",
     "type": "graph",
     "description": "Returns the currently in-flight delete operations.\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_indexing_delete_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Indexing is throttled",
     "type": "graph",
     "description": "Returns if the index is under merge throttling control\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_indexing_is_throttled{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Merges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merges total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_merges_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Merges current",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_merges_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Merges total size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_merges_total_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Merges current size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_merges_current_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Merges total in terms of documents",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_merges_total_docs{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Merges current in terms of documents",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_merges_current_docs{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Merges total time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_merges_total_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Merges throttled time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_merges_total_throttled_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents count",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_docs_count{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Documents deleted count",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_docs_deleted{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Fielddata memory size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_fielddata_memory_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Store size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_store_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Flush total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_flush_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Flush periodic",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_flush_periodic{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Flush total time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_flush_total_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Warmer total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_warmer_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Warmer current",
     "type": "graph",
     "description": "Returns the currently in-flight indexing operations.\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 79 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_warmer_current{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Warmer total time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_warmer_total_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments count",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_count{cluster=~\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Norms memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_norms_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Fixed bit set memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_fixed_bit_set_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Index writer memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_index_writer_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Segments memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Doc values memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_doc_values_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Stored fields memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_stored_fields_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Terms memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_terms_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Version map memory",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 79 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_segments_version_map_memory_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get exists total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_get_exists_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Get missing total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_get_missing_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Get exists time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_get_exists_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    },
    {
     "title": "Get total",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(increase(elasticsearch_stats_total_get_total{cluster=~\"$cluster\", index=~\"$index\"}[$time])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Get time",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "s", "label": "Time spent" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_get_time_in_seconds{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index: {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations",
     "type": "graph",
     "description": "Total number of translog operations that were captured by translog snapshot\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_translog_operations{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Translog size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_translog_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Translog uncommitted operations",
     "type": "graph",
     "description": "Total number of translog operations that were captured by translog snapshot\n\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "max(rate(elasticsearch_stats_total_translog_uncommitted_operations{cluster=~\"$cluster\", index=~\"$index\"}[$__rate_interval])) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Uncommitted size",
     "type": "graph",
     "description": "https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Size in bytes" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_stats_total_translog_uncommitted_size_in_bytes{cluster=\"$cluster\", index=~\"$index\"}) by (index)",
       "legendFormat": "index {{index}}"
      }
     ]
    }
   ]
  }
 ]
}